//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.01 at 06:36:40 PM MSK 
//


package com.romansun.reporting.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Visitors" type="{http://www.example.org/SaveFormalSchema}VisitorsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="month" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="year" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportType", propOrder = {
    "visitors"
})
public class ReportType {

    @XmlElement(name = "Visitors", namespace = "http://www.example.org/SaveFormalSchema", required = true)
    protected VisitorsType visitors;
    @XmlAttribute
    protected Integer month;
    @XmlAttribute
    protected Integer year;

    /**
     * Gets the value of the visitors property.
     * 
     * @return
     *     possible object is
     *     {@link VisitorsType }
     *     
     */
    public VisitorsType getVisitors() {
        return visitors;
    }

    /**
     * Sets the value of the visitors property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisitorsType }
     *     
     */
    public void setVisitors(VisitorsType value) {
        this.visitors = value;
    }

    /**
     * Gets the value of the month property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMonth(Integer value) {
        this.month = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setYear(Integer value) {
        this.year = value;
    }

}
