//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.01 at 06:36:40 PM MSK 
//


package com.romansun.reporting.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VisitorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VisitorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FIO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Lunches" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Dinners" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VisitorType", propOrder = {
    "fio",
    "lunches",
    "dinners"
})
public class VisitorType {

    @XmlElement(name = "FIO", namespace = "http://www.example.org/SaveFormalSchema", required = true)
    protected String fio;
    @XmlElement(name = "Lunches", namespace = "http://www.example.org/SaveFormalSchema")
    protected int lunches;
    @XmlElement(name = "Dinners", namespace = "http://www.example.org/SaveFormalSchema")
    protected int dinners;

    /**
     * Gets the value of the fio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIO() {
        return fio;
    }

    /**
     * Sets the value of the fio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIO(String value) {
        this.fio = value;
    }

    /**
     * Gets the value of the lunches property.
     * 
     */
    public int getLunches() {
        return lunches;
    }

    /**
     * Sets the value of the lunches property.
     * 
     */
    public void setLunches(int value) {
        this.lunches = value;
    }

    /**
     * Gets the value of the dinners property.
     * 
     */
    public int getDinners() {
        return dinners;
    }

    /**
     * Sets the value of the dinners property.
     * 
     */
    public void setDinners(int value) {
        this.dinners = value;
    }

}
