DROP TABLE TALONS;
CREATE TABLE TALONS (
  VISITOR_ID INT
    CONSTRAINT CT_WORK_PK_ID
      PRIMARY KEY,
  FIRSTNAME VARCHAR2(100)
  CONSTRAINT CT_WORK_NN_FIRSTNAME
      NOT NULL,
  LASTNAME VARCHAR2(100)
  CONSTRAINT CT_WORK_NN_LASTNAME
      NOT NULL,
  MIDDLENAME VARCHAR2(100),
  COUNT_LUNCH INT,
  COUNT_DINNER INT
);

DROP SEQUENCE sq_visitor_id;
CREATE SEQUENCE sq_visitor_id
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 10000
  NOCACHE
  NOCYCLE;
  
CREATE OR REPLACE TRIGGER increment_for_visitor
  BEFORE INSERT
  ON talons
  FOR EACH ROW
BEGIN
  IF :NEW.VISITOR_ID IS NULL THEN
    SELECT sq_visitor_id.nextval INTO :NEW.VISITOR_ID
      FROM dual;
  END IF;
END;