//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.01 at 05:43:24 PM MSK 
//


package com.romansun.reports.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VisitorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VisitorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InfoVisitor" type="{http://www.example.org/SaveFormalSchema}InfoVisitorType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VisitorType", propOrder = {
    "infoVisitor"
})
public class VisitorType {

    @XmlElement(name = "InfoVisitor", namespace = "http://www.example.org/SaveFormalSchema", required = true)
    protected InfoVisitorType infoVisitor;

    /**
     * Gets the value of the infoVisitor property.
     * 
     * @return
     *     possible object is
     *     {@link InfoVisitorType }
     *     
     */
    public InfoVisitorType getInfoVisitor() {
        return infoVisitor;
    }

    /**
     * Sets the value of the infoVisitor property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfoVisitorType }
     *     
     */
    public void setInfoVisitor(InfoVisitorType value) {
        this.infoVisitor = value;
    }

}
