CREATE SEQUENCE sq_visitor_id
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 100000
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE sq_association_id
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 10000
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE sq_talons_id
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 100000
  NOCACHE
  NOCYCLE;