CREATE SCHEMA IF NOT EXISTS `talons_db` DEFAULT CHARACTER SET utf8;
CREATE USER IF NOT EXISTS 'talons_admin'@'%' identified BY 'talons_admin_pwd';
GRANT ALL PRIVILEGES ON talons_db.* TO 'talons_admin'@'%';

USE `talons_db`;

DROP TABLE IF EXISTS ASSOCIATIONS;
CREATE TABLE ASSOCIATIONS (
  ASSOCIATION_ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(1000)
);

DROP TABLE IF EXISTS VISITORS;
CREATE TABLE VISITORS (
  VISITOR_ID INT PRIMARY KEY AUTO_INCREMENT,
  FIRSTNAME VARCHAR(100) NOT NULL,
  LASTNAME VARCHAR(100) NOT NULL,
  MIDDLENAME VARCHAR(100),
  ASSOCIATION INT DEFAULT 0 REFERENCES ASSOCIATIONS (ASSOCIATION_ID),
  DESCRIPTION VARCHAR(1000)
);

DROP TABLE IF EXISTS TALONS;
CREATE TABLE TALONS (
  TALON_ID INT PRIMARY KEY AUTO_INCREMENT,
  VISITOR_ID INT REFERENCES VISITORS (VISITOR_ID),
  COUNT_LUNCH INT NOT NULL,
  COUNT_DINNER INT NOT NULL
);

DROP TABLE IF EXISTS VISITOR_TALON;
CREATE TABLE VISITOR_TALON (
  VISITOR_ID INT NOT NULL,
  TALON_ID INT NOT NULL
);

-- indexes on table VISITORS
CREATE INDEX xif04_v ON visitors (association);

-- indexes on table VISITOR_TALON
CREATE INDEX xif05_tv ON visitor_talon (visitor_id);
CREATE INDEX xif06_tv ON visitor_talon (talon_id);

INSERT INTO associations VALUES(0, 'No group', null);