// CREATE TABLE "ASSOCIATIONS"
CREATE TABLE "SYSTEM"."ASSOCIATIONS"
  (
    "ASSOCIATION_ID" NUMBER(*,0),
    "NAME"           VARCHAR2(100 BYTE) CONSTRAINT "CT_ASSOCIATIONS_NN_NAME" NOT NULL ENABLE,
    "DESCRIPTION"    VARCHAR2(1000 BYTE),
    CONSTRAINT "CT_ASSOCIATIONS_PK_ID" PRIMARY KEY ("ASSOCIATION_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SYSTEM" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "SYSTEM" ;

// CREATE TABLE "VISITOR_TALON"
CREATE TABLE "SYSTEM"."VISITOR_TALON"
  (
    "VISITOR_ID" NUMBER(*,0) CONSTRAINT "CT_VT_NN_VISITOR_ID" NOT NULL ENABLE,
    "TALON_ID"   NUMBER(*,0) CONSTRAINT "CT_VT_NN_TALON_ID" NOT NULL ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "SYSTEM" ;

// CREATE TABLE "TALONS"
CREATE TABLE "SYSTEM"."TALONS"
  (
    "TALON_ID"     NUMBER(*,0),
    "VISITOR_ID"   NUMBER(*,0),
    "COUNT_LUNCH"  NUMBER(*,0) CONSTRAINT "CT_TALONS_NN_LUNCHES" NOT NULL ENABLE,
    "COUNT_DINNER" NUMBER(*,0) CONSTRAINT "CT_TALONS_NN_DINNERS" NOT NULL ENABLE,
    CONSTRAINT "CT_TALONS_PK_ID" PRIMARY KEY ("TALON_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SYSTEM" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "SYSTEM" ;


// CREATE TABLE "VISITORS"
CREATE TABLE "SYSTEM"."VISITORS"
  (
    "VISITOR_ID"  NUMBER(*,0),
    "FIRSTNAME"   VARCHAR2(100 BYTE) CONSTRAINT "CT_VISITORS_NN_FIRSTNAME" NOT NULL ENABLE,
    "LASTNAME"    VARCHAR2(100 BYTE) CONSTRAINT "CT_VISITORS_NN_LASTNAME" NOT NULL ENABLE,
    "MIDDLENAME"  VARCHAR2(100 BYTE),
    "ASSOCIATION" NUMBER(*,0) DEFAULT 0,
    "DESCRIPTION" VARCHAR2(1000 BYTE),
    CONSTRAINT "CT_VISITORS_PK_ID" PRIMARY KEY ("VISITOR_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SYSTEM" ENABLE,
    CONSTRAINT "CT_VISITORS_FK_ASSOCIATION_ID" FOREIGN KEY ("ASSOCIATION") REFERENCES "SYSTEM"."ASSOCIATIONS" ("ASSOCIATION_ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "SYSTEM" ;